buildscript {
    repositories {
        mavenCentral()
        google()
    }

    dependencies {
        classpath libs.android.gradle.plugin
        classpath libs.kotlin.gradle.plugin
        classpath libs.ksp.gradle.plugin

        if (System.getenv('IS_GOOGLE_BUILD')) {
            classpath libs.google.gms
        }
    }
}

plugins {
    id 'com.github.triplet.play' version '4.0.0' apply false
    id 'com.github.ben-manes.versions' version '0.54.0' apply false
    id 'se.patrikerdes.use-latest-versions' version '0.2.19' apply false
    id 'io.gitlab.arturbosch.detekt' version '1.23.8' apply false
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven { url "https://jitpack.io" }
    }
}

tasks.register('clean', Delete) {
    delete layout.buildDirectory
}
