pluginManagement {
    includeBuild("../release-tools")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    versionCatalogs {
        sharedLibs {
            from(files("../release-tools/gradle/libs.versions.toml"))
        }
    }
}
include ':app'
include ':common'
include ':proprietary'
include ':foss'
include ':about'
include ':external'
include ':instant'
include ':i18n'
include ':ui'
include ':preferences'
include ':core'
include ':control'
include ':themes'
include ':gdx'
include ':tutorial'
include ':sgtatham'
include ':donation'
include ':wear'
include ':audio'
include ':audio-low'
