plugins {
    id 'io.gitlab.arturbosch.detekt'
    id 'com.android.library'
    id 'kotlin-android'
    id 'com.google.devtools.ksp'
}

android {
    namespace 'dev.lucasnlm.antimine.common'

    defaultConfig {
        // versionCode and versionName must be hardcoded to support F-droid
        minSdk 23
        targetSdk 37
        compileSdk = 37
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlin {
        jvmToolchain(17)
    }

    buildFeatures {
        buildConfig true
        viewBinding true
    }
}

dependencies {

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':core')
    implementation project(':external')
    implementation project(':i18n')
    implementation project(':preferences')
    implementation project(':ui')
    implementation project(':gdx')
    implementation project(':sgtatham')
    implementation project(':sgtatham')

    // AndroidX
    implementation libs.androidx.appcompat
    implementation libs.androidx.preference.ktx
    implementation libs.androidx.recyclerview
    implementation(libs.androidx.activity.ktx) { version { strictly('1.11.0') } }
    implementation(libs.androidx.fragment.ktx) { version { strictly('1.8.9') } }

    // Google
    implementation(libs.material) { version { strictly('1.13.0') } }

    // Constraint
    implementation libs.androidx.constraintlayout

    // Lifecycle
    implementation libs.androidx.lifecycle.viewmodel.ktx

    // Koin
    implementation(libs.koin.android) { version { strictly('4.1.1') } }
    testImplementation(libs.koin.test) { version { strictly('4.1.1') } }

    // Room
    api(libs.androidx.room.runtime) { version { strictly('2.8.0') } }
    api(libs.androidx.room.ktx) { version { strictly('2.8.0') } }
    ksp(libs.androidx.room.compiler) { version { strictly('2.8.0') } }
    testImplementation(libs.androidx.room.testing) { version { strictly('2.8.0') } }

    // Moshi - Json
    api libs.squareup.moshi
    api libs.squareup.moshi.kotlin
    ksp libs.squareup.moshi.kotlin.codegen

    // Coroutines
    implementation(libs.kotlinx.coroutines.core) { version { strictly('1.10.2') } }
    implementation(libs.kotlinx.coroutines.android) { version { strictly('1.10.2') } }
    testImplementation(libs.kotlinx.coroutines.test) { version { strictly('1.10.2') } }

    // Kotlin Lib
    implementation libs.antimine.kotlin.stdlib
    implementation libs.kotlinx.metadata.jvm

    // Unit Tests
    testImplementation libs.junit
    testImplementation(libs.mockito.core) { version { strictly('5.19.0') } }
    testImplementation libs.nhaarman.mockito.kotlin
    testImplementation libs.mockk

    // Core library
    androidTestImplementation libs.androidx.test.core

    // AndroidJUnitRunner and JUnit Rules
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.rules
    androidTestUtil libs.androidx.test.orchestrator
}

tasks.withType(Test).configureEach {
    testLogging {
        exceptionFormat "full"
    }
    afterTest { desc, result ->
        println "Executing test ${desc.name} [${desc.className}] with result: ${result.resultType}"
    }
}
