plugins {
    id 'io.gitlab.arturbosch.detekt'
    id 'com.android.library'
    id 'kotlin-android'
}

android {
    namespace 'dev.lucasnlm.antimine.ui'

    defaultConfig {
        minSdk 23
        targetSdk 37
        compileSdk = 37

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildFeatures {
        buildConfig true
        viewBinding true
    }


    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlin {
        jvmToolchain(17)
    }
}

dependencies {

    implementation project(':core')
    implementation project(':i18n')
    implementation project(':preferences')

    // Google
    implementation(libs.material) { version { strictly('1.13.0') } }

    // AndroidX
    implementation libs.androidx.appcompat
    implementation(libs.androidx.activity.ktx) { version { strictly('1.11.0') } }
    implementation(libs.androidx.fragment.ktx) { version { strictly('1.8.9') } }

    // RecyclerView
    implementation libs.androidx.recyclerview

    // Constraint
    implementation libs.androidx.constraintlayout

    // Lifecycle
    implementation libs.androidx.lifecycle.viewmodel.ktx

    // Koin
    implementation(libs.koin.android) { version { strictly('4.1.1') } }
    testImplementation(libs.koin.test) { version { strictly('4.1.1') } }

    // Coroutines
    implementation(libs.kotlinx.coroutines.core) { version { strictly('1.10.2') } }
    implementation(libs.kotlinx.coroutines.android) { version { strictly('1.10.2') } }
    testImplementation(libs.kotlinx.coroutines.test) { version { strictly('1.10.2') } }

    // Kotlin Lib
    implementation libs.antimine.kotlin.stdlib
    implementation libs.kotlinx.metadata.jvm

    // Unit Tests
    testImplementation libs.junit
    testImplementation(libs.mockito.core) { version { strictly('5.19.0') } }
    testImplementation libs.nhaarman.mockito.kotlin
    testImplementation libs.mockk
}
